HISTFILE=${XDG_STATE_HOME:-$HOME/.local/state}/zsh/history
HISTSIZE=10000
SAVEHIST=10000
HISTORY_IGNORE='(l(s|l|a|la)|cd|z)'

setopt EXTENDED_HISTORY
# setopt HIST_EXPIRE_DUPS_FIRST
# setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
# setopt HIST_NO_FUNCTIONS
# setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
# setopt INC_APPEND_HISTORY_TIME

[[ -d ${HISTFILE:h} ]] || mkdir -p ${HISTFILE:h}
